export const citiesInfo = [
{name: "American",image:"/public/assets/amercianFlag.jpg"},
{name:"British",image:"/public/assets/britishFlag.jpg"},
{name:"Canadian",image:"/public/assets/canadianFlag.jpg"},
{name:"Chinese",image:"/public/assets/chineseFlag.jpg"},
{name:"Croatian",image:"/public/assets/croatianFlag.jpg"},
{name:"Dutch",image:"/public/assets/dutchFlag.jpg"},
{name:"Egyptian",image:"/public/assets/egytianFlag.jpg"},
{name:"Filipino",image:"/public/assets/filipinoFlag.jpg"},
{name:"French", image:"/public/assets/frenchFlag.jpg"},
{name:"Greek",image:"/public/assets/greekFlag.jpg"},
{name:"Indian", image:"/public/assets/indianFlag.jpg"},
{name:"Irish", image:"/public/assets/irishFlag.jpg"},
{name:"Italian", image:"/public/assets/italianFlag.jpg"},
{name:"Jamaican", image:"/public/assets/jamaicanFlag.jpg"},
{name:"Japanese", image:"/public/assets/japaneseFlag.jpg"},
{name:"Kenyan", image:"/public/assets/kenyanFlag.jpg"},
{name:"Malaysian", image:"/public/assets/malaysianFlag.jpg"},
{name:"Mexican", image:"/public/assets/mexicanFlag.jpg"},
{name:"Moroccan", image:"/public/assets/moroccanFlag.jpg"},
{name:"Polish", image:"/public/assets/polishFlag.jpg"},
{name:"Portuguese", image:"/public/assets/portugueseFlag.jpg"},
{name:"Russian", image:"/public/assets/russianFlag.jpg"},
{name:"Spanish", image:"/public/assets/spanishFlag.jpg"},
{name:"Thai", image:"/public/assets/tahiFlag.jpg"},
{name:"Tunisian", image:"/public/assets/tunisianFlag.jpg"},
{name:"Turkish", image:"/public/assets/turkishFlag.jpg"},
{name:"Vietnamese", image:"/public/assets/vietnameseFlag.jpg"}
]