export const citiesInfo = [
{name: "American",image:"/assets/amercianFlag.jpg"},
{name:"British",image:"/assets/britishFlag.jpg"},
{name:"Canadian",image:"/assets/canadianFlag.jpg"},
{name:"Chinese",image:"/assets/chineseFlag.jpg"},
{name:"Croatian",image:"/assets/croatianFlag.jpg"},
{name:"Dutch",image:"/assets/dutchFlag.jpg"},
{name:"Egyptian",image:"/assets/egytianFlag.jpg"},
{name:"Filipino",image:"/assets/filipinoFlag.jpg"},
{name:"French", image:"/assets/frenchFlag.jpg"},
{name:"Greek",image:"/assets/greekFlag.jpg"},
{name:"Indian", image:"/assets/indianFlag.jpg"},
{name:"Irish", image:"/assets/irishFlag.jpg"},
{name:"Italian", image:"/assets/italianFlag.jpg"},
{name:"Jamaican", image:"/assets/jamaicanFlag.jpg"},
{name:"Japanese", image:"/assets/japaneseFlag.jpg"},
{name:"Kenyan", image:"/assets/kenyanFlag.jpg"},
{name:"Malaysian", image:"/assets/malaysianFlag.jpg"},
{name:"Mexican", image:"/assets/mexicanFlag.jpg"},
{name:"Moroccan", image:"/assets/moroccanFlag.jpg"},
{name:"Polish", image:"/assets/polishFlag.jpg"},
{name:"Portuguese", image:"/assets/portugueseFlag.jpg"},
{name:"Russian", image:"/assets/russianFlag.jpg"},
{name:"Spanish", image:"/assets/spanishFlag.jpg"},
{name:"Thai", image:"/assets/tahiFlag.jpg"},
{name:"Tunisian", image:"/assets/tunisianFlag.jpg"},
{name:"Turkish", image:"/assets/turkishFlag.jpg"},
{name:"Vietnamese", image:"/assets/vietnameseFlag.jpg"}
]